### ISSUE TITLE
Finish with only one culomn, why ?

### ISSUE THREAD

**Issue by JocHade** [TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage#47] opened 2020-11-23 18:19 UTC
Under Typo3 10.4.10 (localhost with Xampp)- I followed the documentation step by step, 3 times and I always end with 1 single column instead of 3. Also I do not see the drop-down menu in the backend at the top of the page which gives the possibility to see the columns in a page. Where did I could have screw up?...And i may not be at the good place to ask that question, if so, where should i go ?

**Comment by sypets** [comment] 2020-11-23 18:36
First of all: Thanks for letting us know, that there is a problem. For getting help, you can also check this out https://typo3.org/help (e.g. Slack). But in this case, there may actually be a problem in the documentation, so this is a good place.

So you mean, your default backend layout has only one column? I believe, this was changed a while ago: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Important-81109-SimplifyDefaultBackendLayout.html

You can select a different backend layout for the page  in the page properties > Appearance > Backend Layout (and Backend Layout (subpages of this page). You can also change your default backend layout.

That however requires that your TYPO3 installation already has several backend layouts defined. I don't exactly remember how that is done in this tutorial, please see if this helps you or ask in the resources mentioned on above help page. 

We will also check the documentation, but this may take some time.

More information about backend layouts: https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ApiOverview/BackendLayout/Index.html

**Comment by rhufsky** [comment] 2020-12-06 20:06
I guess @JocHade came across this:

When walking through the **Site Package Tutorial**, at some point in https://docs.typo3.org/m/typo3/tutorial-sitepackage/master/en-us/ContentMapping/Index.html

the reader has to create a page with a three column layout. As far as I found out that the creation of a three column backend layout is not mentioned anywhere in the tutorial, leaving the reader stuck.

So if we assume that the Site Package Tutorial is aimed at newbie, it should work with only things that are available or have been created during the tutorial.

**Comment by sypets** [comment] 2020-12-07 13:15
I absolutely agree - the described procedure should work. The problem here was - (I assume) that the default behaviour was changed in TYPO3.

----

If you have an idea what should be fixed or can make the changes here, you are welcome to create a pull request.

See https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocsOfficial/Index.html

(you can make changes by clicking on "Edit on GitHub" and work directly in the browser or by editing locally and pushing via Git). 

---

This tutorial is being maintained by volunteers and help is very much appreciated.

**Comment by rhufsky** [comment] 2020-12-07 13:32
Usually, when something changes in a system, the docs have to be changed too ;-).

Anyway, in my humble opinion, there is:

- A great site package tutorial, that is aimed probably at persons that are new to TYPO3 world.
- A site package builder that creates an excellent site package which contains a lot of beautiful stuff but is largely undocumented.

A person that is new to TYPO3 has to go through a lot of trial and error since the tutorial and the packages generated by SPB do not match in many cases.

So why not bring both good parts together and write the site package tutorial in a way that it describes the generated site package?

**Comment by sypets** [comment] 2020-12-07 14:31
I agree with you - it should be made easier for people new to TYPO3, not more difficult. 

However, there are possibly some misconceptions:

> since the tutorial and the packages generated by SPB do not match in many cases.

No, they are not indented to match. As far as I am aware that is 2 different ways to do things - the "Site Package Tutorial" handles how to create a site package from scratch.

If you want a tutorial for the site package builder - contact the author of the site package builder or offer to help to create one. Raise the issues with the original authors of this Site Package Tutorial or Site Package Builder - or even better: find ways to help to achieve this. 

I agree with you on your observations - I also find the various ways to do things often confusing (for newcomers) - the problem is someone needs to do something about this - it cannot always be the documentation team, it cannot always be the people who are already doing a lot in their spare time for free. 

---

As I already wrote in another comment: find ways to contribute and make it happen. 

* Slack: #typo3-documentation
* [Contribute](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocsOfficial/Index.html)
* [Ways to help  ](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocsOfficial/HowYouCanHelp.html)
* [Join docs team](https://typo3.org/community/teams/documentation).

**Comment by rhufsky** [comment] 2020-12-07 15:05
I totally agree with you, no none hould have more on her or his to do list that she or he can possibly handle.

The site package builder is maintained by someone who I perceived to be part of the TYPO3 team, so without knowing too much about who is responsible for what, it seemed  to be reasonable to contact the documentation team. Please forgive me,if that was not a correct assumption.

From the perspective of the TYPO3 team it totally makes sense to only describe what is part of TYPO3, and not what an extension does.

For an external person things are getting a bit blurred. We want to get up to speed with site packages as fast as possible. and from this perspective a package builder with matching documentation would be helpful.

Maybe my suggestion to unify site package builder and site package tutorial has to be posted somewhere else, I would appreciate any hints here.

Personally I am in the process of writing a manual for a site package generated by the builder for my own purposes. This manual adresses a number of things that I found out via research and community help. When this reaches a reasonable state I would be more than happy to provide it to the community.

**Comment by tomwarwick** [comment] 2020-12-07 15:21
Hi Robert,

I share your frustrations. Having worked on Site Package documentation in the past and as a frequent user of the Site Package builder, I'd be more than happy to work with you on your manual, if you'd like to get involved please reach out.

**Comment by JocHade** [comment] 2020-12-07 17:00
Good morning all,

Thank you all for your answers. 

The tutorial should indeed contain all the information so that a beginner can get to build the sitepackage. The documentation is well done, the steps and the description are good and allow to understand the idea behind the fluidtemplating. 

The only problem I encountered concerns the creation of the 3 columns, the code contained in [the page](https://docs.typo3.org/m/typo3/tutorial-sitepackage/master/en-us/ContentMapping/Index.html)  at Typoscript Mapping in Fluid Template, if I understood correctly should display them, but at the end when I open the site I only have one in the backend for the editors and in the frontend of the site. I solved the problem by choosing 3 columns in edit page / appearence / 3columns. Of course for this to work you have to have bootstrap installed, which was the case because I had the Introduction package installed. I don't know if without this package I would have had the possibility to modify the number of columns. 

I also wondered if the fact that I have version 10.4.10 of Typo3 would be the source of the problem as the images in the tutorial show version 8.7.

**Comment by rhufsky** [comment] 2020-12-07 17:13
When you have a minimal site package without bootstrap package or introduction package, you will not get the 3 columns backend layout.

The 3 columns backend layout is part of bootstrap package which is included in introduction package. The site package tutorial seems to be aimed at a very minimalistic setup so it rightfully does not mention bootstrap package.

Bootstrap package brings a ton of templates, backend layouts, content elements and other goodies.

**Comment by rhufsky** [comment] 2020-12-07 18:19
> Hi Robert,
> 
> I share your frustrations. Having worked on Site Package documentation in the past and as a frequent user of the Site Package builder, I'd be more than happy to work with you on your manual, if you'd like to get involved please reach out.

Lets do that,

what I have now is a bit cobbled together:

04-TYPO3-Templating-Basics.pdf – minimal basics of TypoScript, Fluid Templates, Backend Layouts, Layouts/Templates/Partials, all without a site package, to help keeping focus.
05-TYPO3-Site-Package.pdf – generate a site package, anatomy of a site package, backend layout mapping, dynamic content mapping, Javascript.

I write everything in markdown, the samples are converted to PDF to avoid the hassle with embedded images.

All is very raw at this stage and definitely not ready for the public, but lets see your take on this.

Kind regards
[04-TYPO3-Templating-Basics.pdf](https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage/files/5654466/04-TYPO3-Templating-Basics.pdf)
[05-TYPO3-Site-Package.pdf](https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage/files/5654467/05-TYPO3-Site-Package.pdf)

**Comment by gilbertsoft** [comment] 2021-06-28 19:31
There should be a link to this page:
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/BackendLayout/Index.htmlhttps://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/BackendLayout/Index.html

**Comment by linawolf** [comment] 2021-09-12 12:34
I am currently working on integrating backend layouts in both the tutorial and the underlying example site_package.

**Closed** 2021-09-19 13:18 UTC
